name: Format Python Code

on:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  format:
    name: Format with Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install "black[jupyter]"

      - name: Format code with Black
        run: black .
        
      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Reformat code using black"
          git push --force --quiet https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
